require File.join(File.dirname(__FILE__), "test_helper")

class PendingScenarioTest < Test::Unit::TestCase
  context "A test generated by a pending Scenario, when executed" do
    should "output a 'P' instead of a '.'"
  end
end
