# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{coulda}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Evan David Light"]
  s.date = %q{2009-09-12}
  s.description = %q{Behaviour Driven Development derived from Cucumber but as an internal DSL with methods for reuse}
  s.email = %q{evan@tiggerpalace.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "HISTORY",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "coulda.gemspec",
     "example/sample.rb",
     "lib/coulda.rb",
     "lib/coulda/feature.rb",
     "lib/coulda/scenario.rb",
     "test/feature_test.rb",
     "test/scenario_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://evan.tiggerpalace.com/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{Behaviour Driven Development derived from Cucumber but as an internal DSL with methods for reuse}
  s.test_files = [
    "test/feature_test.rb",
     "test/scenario_test.rb",
     "test/test_helper.rb"
  ]
  s.add_dependency 'jeremymcanally-pending', '>= 0.1'

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
