#!/usr/bin/env ruby

################################################################################
# notify
#
# This hook is reponsible for notifying the user of the results of a task, such
# as a Continuous Integration build.
#
# PARAMETERS:
#
# This hook will be called with the form:
#
#   .devver/hooks/notify TASK EXIT_STATUS
#
# * TASK is the name of the task that triggered the notification
# * EXIT_STATUS is the numeric exit status of the task. 0 indicates success.
#
# INPUT:
#
# This hook will be provided with a transcript of the triggering task's output.
# Both STDOUT and STDERR output will be included in the transcript.
#
# OUTPUT:
#
# This task should exit with a 0 status if the notification was successful, and
# a nonzero status if the notification failed.
#
################################################################################
require 'net/smtp'
require 'time'
to              = "danmayer@gmail.com"

success         = ARGV[0].to_i == 0
recipient       = ENV.fetch('NOTIFY_RECIPIENT'){to}
message = <<"EOF"
From: support@devver.net
To: #{recipient}
Subject: Build #{success ? 'succeeded' : 'failed'}
Date: #{Time.now.rfc2822}
The task "#{ARGV[1]}" #{success ? 'succeeded' : 'failed'}.

Output:

#{$stdin.read}
EOF

Net::SMTP.start('localhost', 25) do |smtp|
  smtp.send_message(message, 'application@devver.net', recipient)
end
