#!/bin/sh

################################################################################
# prepare_database
#
# Learn more about when Devver attempts to use a database below:
# http://support.devver.net/faqs/configuration/database-configuration
#
# This hook is responsible for preparing a database to have tests run against
# it.  The database will already exist when this hook is executed.
################################################################################

# The following command will initialize the test database in a typical Ruby on
# Rails project.  It creates the database tables according to the values in
# schema.rb, which is created when rake db:migrate is run.
#rake RAILS_ENV=test db:schema:load

# For some Rails projects, it may be desirable to migrate from zero instead of
# loading the schema.  In that case, comment out any other commands and
# uncomment the following line:

# RAILS_ENV=test rake db:migrate

# *** NOTE FOR UPGRADING USERS ***
#
# If you previously customized your project's database initialization using the
# .devver/devver_opts.yml file, you will need to copy that configuration into
# this file.  Look for the line beginning with "DATABASE_INITIALIZATION:", and
# copy the value into this file.  Make sure that all other commands in this file
# are commented out.
